services:
  pythontelegrambottemplate:
    #image: ghcr.io/<ваш профиль гит хаб>/<назввание репозитория>
    image: pythontelegrambottemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "${TZ}"
      BOT_TOKEN: "${BOT_TOKEN}"
      PYTHONPATH: "${PYTHONPATH}"
    # либо просто
    # env_file:
    #   - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
